### PR TITLE
Handle `LNot` for float in forward evaluation and refinement on guards

### LINKED ISSUE #1211: `LNot` on floating-point values
## Refine
Extracted from concrat/axel, Goblint crashes on this:
```c
int main() {
  double x;
  if (!x) // TODO NO CRASH: Invalid_argument("Cilfacade.get_ikind: non-integer type double ")
    return 1;
  return 0;
}
```
The exception comes from here:
https://github.com/goblint/analyzer/blob/8468a5a676fae48a82e0284ea13170d0cefa935c/src/analyses/baseInvariant.ml#L570-L581

The problem is that even though the result type of the `LNot` expression is always integer, `e` underneath might be a float.

## Eval
The forward evaluation of `LNot` on floats is also incorrect:
https://github.com/goblint/analyzer/blob/8468a5a676fae48a82e0284ea13170d0cefa935c/src/analyses/base.ml#L186-L194
It returns a `Float` abstraction even though for `LNot` it should return an `Int` abstraction. This mismatch can cause a similar issue as #1209 when a `Float` is stored for an integer variable.

### PR DESCRIPTION
**Pull request by michael-schwarz**
Fixes the issues identified by @sim642 where 
- the type of the abstract values for expressions involving `LNot` was wrong
- having `!x` for float variables `x` in a guard lead to crashes

Closes #1211.

### CODE REVIEW

File: src/analyses/base.ml [hunk 1]
```diff
@@ -178,14 +178,15 @@ struct
     | LNot -> ID.lognot
 
   let unop_FD = function
```
Comment (sim642) [inline src/analyses/base.ml:180]: There's also a copy in `BaseInvariant` apparently. Maybe these could be deduplicated in `BaseUtil`, `ValueDomain` or something?

File: src/analyses/base.ml [hunk 2]
```diff
@@ -178,14 +178,15 @@ struct
...
-    | Neg  -> FD.neg
+    | Neg  -> (fun v -> (Float (FD.neg v):value))
+    | LNot -> (fun c -> Int (FD.eq c (FD.of_const (FD.get_fkind c) 0.)))
     (* other unary operators are not implemented on float values *)
-    | _ -> (fun c -> FD.top_of (FD.get_fkind c))
+    | _ -> (fun c -> Float (FD.top_of (FD.get_fkind c)))
```
Comment (sim642) [inline src/analyses/base.ml:184]: Since `BNot` is the only remaining option, we should just explicitly match that and say it isn't type-valid anyway on a float.

**Review by sim642 — APPROVED** [review]
