### PR TITLE
Fix address set meet

### LINKED ISSUE #925: Address set meet unsound for addresses with different int domains active
The meet of the address set is unsound for addresses when different integer domains are active in these addresses. An example is given [here](https://github.com/goblint/analyzer/blob/3dd39e7abbe813ad63fe0137e6a1e17fcaa506c1/tests/regression/29-svcomp/31-dd-address-meet.c).

### PR DESCRIPTION
**Pull request by jerhard**
The meet of addresses is currently unsound when different integer domains may be activated within an analysis run. This is demonstrated by this [example](https://github.com/goblint/analyzer/blob/d35bc54f50531b0f4c98951df55bbcf04b7be04c/tests/regression/29-svcomp/31-dd-address-meet.c). Here, the abstract representation of the address pointed to by `slotvec0.val` contains an offset where all int domains are active, as all int domains are activated for global variables with the `annotation.int.enabled` setting. At the point of the comparison however, only `def_exc` is active. Therefore the abstract addresses are kept in different buckets and the meet that is performed yields `bottom`.

This issue also appears on sv-comp when the congruence auto-tuning is enabled, and for *some* functions the congruence domain is activated, and for others not. 

This PR fixes this issue by not keeping the `index` information in the representative that is used to split address sets.

(Closes #925)

### CODE REVIEW

**Comment by sim642** [comment]
> This PR fixes this issue by not keeping the `index` information in the representative that is used to split address sets.

But that is already the case:
https://github.com/goblint/analyzer/blob/00bfa7f52f303c2bb7007eb3a0f1085b7cae1e46/src/cdomains/lval.ml#L389-L399

Isn't this just another instance of #822?

**Comment by michael-schwarz** [comment]
The issue is `Idx.top ()` that depends on the activated int domains.

File: src/cdomains/lval.ml [hunk 1]
```diff
@@ -385,22 +385,90 @@ end
 module NormalLatRepr (Idx: IntDomain.Z) =
 struct
   include NormalLat (Idx)
+  module Offset = struct
```
Comment (michael-schwarz) [inline src/cdomains/lval.ml:388]: Can we maybe change this module name to something such as `ReprOffset` to make it clear that it is distinct from normal offsets?

File: tests/regression/29-svcomp/31-dd-address-meet.c [hunk 2]
```diff
@@ -0,0 +1,25 @@
+// PARAM: --enable annotation.int.enabled
```
Comment (michael-schwarz) [inline tests/regression/29-svcomp/31-dd-address-meet.c:1]:
```suggestion
// PARAM: --enable annotation.int.enabled
// This option enables ALL int domains for globals
```

**Comment by sim642** [comment]
> The issue is `Idx.top ()` that depends on the activated int domains.

That seems like a problem in itself because it's supposed to be a real top, not `top_of`. Having multiple incomparable "tops" defies the definition of top.

Also, this is the index domain, which is a separate thing from the intdomain that's actually used for integer values.

> In the example the two address values for which the meet is `\bot` are identical except for the number of activated int domains.

It still seems to me that something deeper is wrong here that such situation can arise at all. Aren't the intdomain projections that are used for converting integer abstractions between different precisions supposed to ensure that we don't have such mixture?
There might be a projection missing somewhere. If it's a problem here, it's a problem elsewhere as well because AFAIK our intdomain operations aren't meant to be used between tuples with different precisions. The fact that such mismatches arise at all is the bug.
If integers with mismatching precisions coexist, then other operations on them could break precisely in the same way.

File: src/cdomains/lval.ml [hunk 3]
```diff
@@ -385,22 +385,94 @@ end
 module NormalLatRepr (Idx: IntDomain.Z) =
 struct
   include NormalLat (Idx)
+  module ReprOffset = struct
```
Comment (sim642) [inline src/cdomains/lval.ml:388]: This is all just copy-paste from existing code... `Lval.offs` is polymorphic in both offset types, so the existing type can simply be reused. `Lval.OffsetPrintable` is a functor, so it could simply be instantiated with a different (unit) index domain without copying all this code.

**Review by sim642 — CHANGES_REQUESTED** [review]

File: src/cdomains/lval.ml (hunk 3 above)
Comment (jerhard) [reply src/cdomains/lval.ml:388]: Yes, good idea! I now created PR #926 that implements that approach. Since we might want to still merge the current PR first (because we already have a benchmark running), I made it a separate PR.
