### PR TITLE
Fix handling of labels in unrolling & add possibility to run CIL checks on CFGs

### LINKED ISSUE #895: Loop Unrolling Fails for `do { } while(0)` Loop contained in a switch
Minimal example:

~~~C
// PARAM: --set exp.unrolling-factor 1
int main()
{
  int m;
  int i =0;

  switch (m)
  {
    default:
      do { } while (0);
  }
  return 0;
}
~~~

fails with

```
Fatal error: exception Not_found
Raised at Stdlib__Hashtbl.MakeSeeded.find in file "hashtbl.ml", line 393, characters 21-36
Called from BatOption.map in file "src/batOption.ml", line 37, characters 19-24
Called from Goblint_lib__Constraints.FromSpec.tf in file "src/framework/constraints.ml", line 710, characters 17-53
Called from BatList.map in file "src/batList.mlv", line 239, characters 23-28
Called from Goblint_lib__Constraints.FromSpec.system.tf in file "src/framework/constraints.ml", line 740, characters 27-47
Called from Goblint_lib__Constraints.EqConstrSysFromGlobConstrSys.conv in file "src/framework/constraints.ml", line 876, characters 4-105
```

This causes issues where some 33 tasks go from correct to `Exception(Not_found)`  in SV-Comp 23 when enabling the auto-tuner for loop unrolling.

### PR DESCRIPTION
**Pull request by michael-schwarz**
Our handling of labels when unrolling loops was still slightly off:

- We did not populate the `labelAlphaTable`, so there were collisions possible with labels defined outside the loop that is being unrolled, as we started from a fresh alpha table.
- We were excessively copying statements (not leaving the original statement in the CFG as well (at the very end), causing `goto`s from outside the CFG to point to  statements that were not included in the current CFG anymore.

To catch such issues early from now on, I added the option `dbg.run_cil_check` that causes CIL integrity checks to run and enabled them for our loop unrolling tests.

**TODO:**

- [x] Wait for merge of https://github.com/goblint/cil/pull/121 and update pins

Closes #895

### CODE REVIEW

**Comment by michael-schwarz** [comment]
comparison

It has an overwhelmingly positive impact if we do this and enable the loop autotuning. The instances in which we are unsound remain to be investigated, they may already be fixed upstream in SV-Comp.

For overflows, we succeed with an additional 14 tasks, for no-data-race it makes no difference.

File: tests/regression/55-loop-unrolling/09-weird.c [hunk 1]
```diff
@@ -0,0 +1,13 @@
+// PARAM: --set exp.unrolling-factor 2 --enable dbg.run_cil_check
```
Comment (sim642) [inline tests/regression/55-loop-unrolling/09-weird.c:1]:
```suggestion
// PARAM: --set exp.unrolling-factor 2 --enable dbg.run_cil_check
#include <goblint.h>
```

File: src/util/loopUnrolling.ml [hunk 2]
```diff
@@ -446,9 +446,6 @@ class loopUnrollingVisitor(func) = object
           annotateArrays b;
           match s.skind with
           | Loop (b,loc, loc2, break , continue) ->
-            (* We copy the statement to later be able to modify it without worrying about invariants *)
-            let s = { s with sid = s.sid } in
```
Comment (sim642) [inline src/util/loopUnrolling.ml:450]: Why is this now unnecessary? To the contrary, in https://github.com/goblint/analyzer/pull/563#discussion_r789751464 it was deemed necessary.

**Comment by michael-schwarz** [comment]
The unsound cases are all LDV-related, maybe you can have a look @sim642 since you looked into some similar ones as well.

- c/ldv-linux-3.16-rc1/205_9a_array_unsafes_linux-3.16-rc1.tar.xz-205_9a-drivers--net--ppp--ppp_generic.ko-entry_point.cil.out.yml
- c/ldv-linux-3.16-rc1/205_9a_array_unsafes_linux-3.16-rc1.tar.xz-205_9a-drivers--net--wan--hdlc_cisco.ko-entry_point.cil.out.yml
- c/ldv-linux-3.16-rc1/205_9a_array_unsafes_linux-3.16-rc1.tar.xz-205_9a-drivers--net--wan--hdlc_fr.ko-entry_point.cil.out.yml
- c/ldv-linux-3.16-rc1/205_9a_array_unsafes_linux-3.16-rc1.tar.xz-205_9a-drivers--net--wireless--mwifiex--mwifiex_sdio.ko-entry_point.cil.out.yml
- c/ldv-validator-v0.6/linux-stable-431e8d4-1-102_1a-drivers--net--r8169.ko-entry_point.cil.out.yml
- c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-08_1a-drivers--md--dm-cache.ko-entry_point.cil.out.yml
- c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-08_1a-drivers--staging--comedi--comedi.ko-entry_point.cil.out.yml
- c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-32_7a-drivers--md--dm-crypt.ko-entry_point.cil.out.yml
- c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-32_7a-drivers--media--v4l2-core--videodev.ko-entry_point.cil.out.yml

At this point I am fairly convinced that the tasks are at fault, and would propose to merge this regardless (and in the worst case if we can not fix the benchmarks before keep the autotuner option for loop unrolling off for sv-comp).

File: src/util/loopUnrolling.ml (hunk 2 above)
Comment (michael-schwarz) [reply src/util/loopUnrolling.ml:450]: Yes, it was, because it covered up some other bugs. After those are now fixed, it is correct to keep one copy of the statement identical: Since loops are unrolled bottom-up, first the innermost loop gets duplicated (with the last instance remaining the same). Then, the outer loop is unrolled, maintaining the invariant that there is at most one copy.

**Comment by michael-schwarz** [comment]
> Would be good to look into at least some of them to determine what's at fault and whether we will be able to do something about them any more after the tasks are frozen.

Iirc, if we find UB, we can still move to exclude those tasks, right?

File: tests/regression/55-loop-unrolling/09-weird.c (hunk 1 above)
Comment (michael-schwarz) [reply tests/regression/55-loop-unrolling/09-weird.c:1]: Include `goblint.h` header

**Comment by sim642** [comment]
I looked up if any of those have been modified/have open MRs in sv-benchmarks and added links for those.

It is possible to exclude tasks after freezing by proposing changes, but getting those merged is more difficult since "pull requests after deadline only merged after jury approval".
But either way, since loop unrolling is currently disabled, we can keep it disabled until all of those tasks have been handled.

**Comment by michael-schwarz** [comment]
**c/ldv-linux-3.16-rc1/205_9a_array_unsafes_linux-3.16-rc1.tar.xz-205_9a-drivers--net--wan--hdlc_cisco.ko-entry_point.cil.out.i**


- `ldv_check_final_state()` checks that `ldv_set_is_empty()` returns a non-zero value
- `ldv_set_is_empty()` is `return (last_index == 0);`
- `last_index` is a global initalized to zero
-  It is modified from `ldv_set_add` and `ldv_set_remove` (which are both uncalled)

- `ldv_set_add` is uncalled and called
    - from `ldv_skb_alloc` (which is uncalled)
        - it is called from `ldv_dev_alloc_skb_12` (which is uncalled)
            - which is called from `cisco_keepalive_send` (which is uncalled)
                - called from `cisco_rx` (where `skb->len <= 3U` is always true and the call to `cisco_keepalive_send` is never performed)
                    - skb is a pointer to `proto_group1` which is initialized to `0` in `ldv_initialize_hdlc_proto_3` and never assigned any different value

    - and from `ldv_netdev_alloc_skb` (which is uncalled)
        - it is called from `ldv_dev_alloc_skb` (which is completely uncalled)

- `ldv_set_remove` only changes `last_index` if it is positive (and thus does not modify it here)

File: tests/regression/55-loop-unrolling/09-weird.c (hunk 1 above)
Comment (sim642) [reply tests/regression/55-loop-unrolling/09-weird.c:1]: Nothing was actually changed here.

**Comment by sim642** [comment]
I opened a new issue about these unsound cases to not block this PR.

**Review by sim642 — APPROVED** [review]
