### PR TITLE
Fix pointer arithmethic on NULL

### LINKED ISSUE #1762: May-NULL plus may-zero yields non-NULL pointer
This is a minimization of an issue found by @Robotechnic:
```c
int main(void) {
    int *p;
    int i;
    int *q = p + i;
    *q = 42; // TODO WARN (may NULL dereference)
}
```
We currently do not output a NULL dereference warning from base, even though `p` may be `NULL` and `i` may be 0.
It looks like our pointer arithmetic misses this possibility, because we get that `q → {?}`, which means non-`NULL` only, but no `NULL`.

### PR DESCRIPTION
**Pull request by sim642**
Closes #1762.

### CODE REVIEW

File: src/analyses/base.ml [hunk 1]
```diff
@@ -303,24 +303,28 @@ struct
...
-      | None -> default addr
+      match addr with
+      | Addr (x, o) -> AD.of_mval (x, addToOffset n (Some x.vtype) o)
+      | NullPtr ->
+        begin match ID.equal_to Z.zero n with
+          | `Eq -> AD.null_ptr
+          | `Neq -> AD.unknown_ptr
+          | `Top -> AD.top_ptr
+        end
+      | UnknownPtr
```
Comment (michael-schwarz) [inline src/analyses/base.ml:314]: Can the unknown pointer not become a null pointer by pointer arithmetic?

Comment (sim642) [reply src/analyses/base.ml:314]: Indeed, a similar case split might have to be here.

**Review by michael-schwarz — APPROVED** [review]
