### PR TITLE
Read offsets separately in eval_rv_base for pointer dereference

### LINKED ISSUE #716: Different field access on imprecise address set
I continued looking at chrony after #712 and found another little bit of unsoundness: the callback function `name_resolve_handler` is never called.
The problem is that at an intermediate level of callbacks in `sched.c`, the eventual callback `name_resolve_handler` is stored in the intermediate callback's opaque argument, which ends up being an ambiguous set of addresses pointing to structs of different types. This is because in other places the same `sched.c` mechanism is used for something else as well. Later when trying to access a particular field of that, we immediately get `VD.top` since simple structs are implemented using a `MapTop` domain, where looking up the other struct's field gives the default `VD.top`.

I've extracted the problem to https://github.com/goblint/analyzer/tree/ambig-field. A minimized test case is the following: https://github.com/goblint/analyzer/blob/ab70c9b0e1301ad6dd90044cc8c4986139429da1/tests/regression/01-cpa/56-ambig-field.c#L21-L38

### Simple structs
Tracing the program reveals the two structs being joined, giving an empty struct (remember, this is `MapTop`, which is reversed):
```
          %%% get: Singlethreaded mode.
          %%% get: var = mapping {
                           f1 ->   {&foo}
                         }, {&s1} = mapping {
                                        f1 ->   {&foo}
                                      }
          %%% get: Singlethreaded mode.
          %%% get: var = mapping {
                           f2 ->   {&bar}
                         }, {&s2} = mapping {
                                        f2 ->   {&bar}
                                      }
          %%% get: Result: mapping {
                             }
```
Then of course accessing either field on the result returns `VD.top` and completely forgets the known pointers.

### Set structs
One might hope that a more powerful structs domain (`sets`) would help here, but no:
```
          %%% get: Singlethreaded mode.
          %%% get: var = {mapping {
                            f1 ->   {&foo}
                          }}, {&s1} = {mapping {
                                           f1 ->   {&foo}
                                         }}
          %%% get: Singlethreaded mode.
          %%% get: var = {mapping {
                            f2 ->   {&bar}
                          }}, {&s2} = {mapping {
                                           f2 ->   {&bar}
                                         }}
          %%% get: Result: {mapping {
                              f1 ->   {&foo}
                            }, mapping {
                                   f2 ->   {&bar}
                                 }}
        %%% cast: (tests/regression/01-cpa/56-ambig-field.c:34:3-34:43)
  cast {mapping {
          f1 ->   {&foo}
        }, mapping {
               f2 ->   {&bar}
             }} from ? to struct S1  is {mapping {
                                             f1 ->   Unknown
                                           }}!
```
Here the join preserves both possibilities as a set, but then casting them elementwise to the particular struct type will still give `VD.top` in the field, again forgetting the known pointers.

### Further thoughts
The thing to note here (which I was also surprised by) is that when looking up fields from ambiguous addresses, we don't apply `eval_offset` on each ambiguous possibility separately and then join the results, but instead join the structs and apply one `eval_offset` on the joined result. So the base analysis is super non-relational here, which makes this additionally annoying to fix. If it was the other way around, it would be possible in base to only filter out the possibilities, where the offset actually exists. In its current form, the struct domain must at the intermediate stage be able to represent the ambiguous struct and then allow `eval_offset` to just use the field it needs, ignoring other possibilities.

It's very much possible that we have the same problem on zstd as well (it might even be the source of the `VD.top`s we try to ignore with #707) because the overall construction is the same: each job is represented by a struct consisting of a function pointer and an opaque argument pointer to it. Since we are so non-relational here, we end up passing all the possible argument pointers (to structs of different types) to all the function pointers. Most of these combinations are nonsense, but we don't say anything, don't assume anything, but just become very imprecise (to the point of unsoundness by forgetting function pointers that might be called).

### PR DESCRIPTION
**Pull request by jerhard**
This PR changes the treatment of pointer dereference `eval_rv_base` and the `Structs.get` method, to avoid producing top in the cases described in #716. 

The change affects the case that `eval_rv_base` evaluates a pointer that is dereferenced and some offset is taken from the resulting value. Previously, all objects that the pointer could point to without the offset. Then, these memory objects were joined, and the offset was taken from the result. This led to additional imprecision in case of the join of e.g. structs of different type. 

Now, `eval_rv_base` will look at all the possible target addresses, and read for each of them the value at the offset. Then, the values at the offsets are joined, to produce the result. 
The struct domain is changed such that `get` yields a `top_value` of the corresponding type, rather than `'Top`. This way, if a field of pointer type is requested, but the abstract value does not contain the field, a top pointer (`{?, NULL}`) is constructed instead of `'Top`.  By avoiding to produce the `'Top` in this case, addresses are read from structs of the appropriate type are kept in the result of the join.  

Closes #716.

### CODE REVIEW

**Comment by jerhard** [comment]
When the list of malloc-wrappers is provided to Goblint, this also fixes the issue of warnings for no suitable function existing for dynamic function calls dereferencing pointers with some field offset, e.g.:

 ```
[Warning][Unsound] Unknown call to function *(inst->handler). (nameserv_async.c:94:4-94:66)
[Warning][Unsound] No suitable function to be called at call site. Continuing with state before call. (nameserv_async.c:94:4-94:66)
```
There remain four cases of `"No suitable function to be called at call site. Continuing with state before call"`, however, these are cases, where the function pointer is only ever set to `Null` (and nothing else). So this is not an issue caused by the analysis.

**Comment by sim642** [comment]
> Now, `eval_rv_base` will look at all the possible target addresses, and read for each of them the value at the offset. Then, the values at the offsets are joined, to produce the result.

This replaces one `eval_offset` with as many as there are elements in the address set, which could have a performance impact.
I suppose the Munich benchmarking server is currently busy with interactive, so I'll do the benchmarks on the Tartu server.

File: src/analyses/base.ml [hunk 1]
```diff
@@ -801,43 +801,49 @@ struct
...
+          v'
         in
-        let v' = VD.cast t v in (* cast to the expected type (the abstract type might be something other than t since we don't change addresses upon casts!) *)
-        if M.tracing then M.tracel "cast" "Ptr-Deref: cast %a to %a = %a!\n" VD.pretty v d_type t VD.pretty v';
-        let v' = VD.eval_offset a (fun x -> get a gs st x (Some exp)) v' (convert_offset a gs st ofs) (Some exp) None t in (* handle offset *)
-        let v' = do_offs v' ofs in (* handle blessed fields? *)
-        v'
+        let addresses = AD.elements p in
+        let values = List.map (fun e -> do_single_address (AD.singleton e)) addresses in
+        List.fold VD.join (VD.bot ()) values
```
Comment (sim642) [inline src/analyses/base.ml:846]: We should avoid the intermediate lists and just do a `AD.fold`.

Actually I was wondering where the `VD.join`-ing before this change was, because it doesn't show in the diff, but apparently that's part of `get`. This just breaks an address set to a set of singleton address sets, such that in `get` no `VD.join`-ing takes place.

Comment (jerhard) [reply src/analyses/base.ml]: >We should avoid the intermediate lists and just do a AD.fold.

Yes, good idea, it now does this.

**Review by sim642 — APPROVED** [review]

**Comment by jerhard** [comment]
Thanks for benchmarking this! Good to know that it does in general not have a negative impact on performance.
