### PR TITLE
Make Mutex-Meet Privatizations sound for Reentrant Locks

### LINKED ISSUE #454: Investigate how mutex-meet privatization plays together with re-entrant mutexes
It currently seems like it is no problem, as the calls used to set the type of a mutex to recursive are unknown calls, leading to an invalidation of all globals.

~~~C
// SKIP PARAM: --set ana.activated[+] apron --set ana.path_sens[+] threadflag --sets exp.apron.privatization mutex-meet --sets exp.privatization mutex-meet --disable sem.unknown_function.invalidate.globals --disable sem.unknown_function.spawn
#include <stdio.h>
#include <stdlib.h>
#include <pthread.h>
#include <string.h>
#include <signal.h>

pthread_mutex_t mt;
int i = 0;

void* fn1(void* agr)
{
  int err;

  pthread_mutex_lock(&mt);
  i = 5;
  pthread_mutex_lock(&mt);
  assert(i == 5); //TODO
  i = 0;
  pthread_mutex_unlock(&mt);
  pthread_mutex_unlock(&mt);
}


int main()
{
  pthread_t tid1;

  pthread_mutexattr_t mat;
  pthread_mutexattr_init(&mat);

  //The type of lock set is recursive
  pthread_mutexattr_settype(&mat, PTHREAD_MUTEX_RECURSIVE);
  pthread_mutex_init(&mt, &mat);

  pthread_create(&tid1, NULL, fn1, NULL);

  pthread_join(tid1,NULL);
  pthread_mutex_destroy(&mt);
}
~~~

If we set `--disable sem.unknown_function.invalidate.globals --disable sem.unknown_function.spawn`, we get into a situation where the fixpoint is not reached:

```
[Warning][Unknown] Function definition missing for pthread_mutexattr_init (tests/regression/36-apron/96-reentrant.c:30:3)
[Warning][Unknown] Invalidating expressions: AddrOf(Var(mat,
                                     NoOffset)) (tests/regression/36-apron/96-reentrant.c:30:3)
[Warning][Unknown] Unknown value in {&mat} could be an escaped pointer address! (tests/regression/36-apron/96-reentrant.c:30:3)
[Warning][Unknown] Function definition missing for pthread_mutexattr_settype (tests/regression/36-apron/96-reentrant.c:33:3)
[Warning][Unknown] Invalidating expressions: AddrOf(Var(mat, NoOffset)), Const(Int64(1,int,None)) (tests/regression/36-apron/96-reentrant.c:33:3)
[Warning][Unknown] Unknown value in {&mat} could be an escaped pointer address! (tests/regression/36-apron/96-reentrant.c:33:3)
[Warning][Assert] Assertion "i == 0" is unknown. Expected: SUCCESS -> failed (tests/regression/36-apron/96-reentrant.c:18:3)
Fixpoint not reached at mt on tests/regression/36-apron/96-reentrant.c:8:17
Origin: node 24 "return (0);" on tests/regression/36-apron/96-reentrant.c:40:1
 Solver computed:
 [Apron:bottom (env: [|0> i:int|]), readwrite * write:({}, All mutexes),
  value domain:mapping {
                 Global {
                   _IO_2_1_stdin_ ->   mapping {
                                         }
                   _IO_2_1_stdout_ ->   mapping {
                                          }
                   _IO_2_1_stderr_ ->   mapping {
                                          }
                   stdin ->   {NULL, ?}
                   stdout ->   {NULL, ?}
                   stderr ->   {NULL, ?}
                   sys_nerr ->   (Unknown int([-31,31]))
                   sys_errlist ->   (Array: {}, (Unknown int([-63,63])))
                   __tzname ->   (Array: {}, (2))
                   __daylight ->   (Unknown int([-31,31]))
                   __timezone ->   (Unknown int([-63,63]))
                   tzname ->   (Array: {}, (2))
                   daylight ->   (Unknown int([-31,31]))
                   timezone ->   (Unknown int([-63,63]))
                   _sys_siglist ->   (Array: {}, (65))
                   sys_siglist ->   (Array: {}, (65))
                   i ->   (0)
                 }
               }, Unit:(), Unit:(), Unit:(), raw bools:false, Unit:(), Unit:()]
 Side-effect:
 [readwrite * write:({}, All mutexes), Apron:top (env: [||]), Unit:(), Unit:(),
  Unit:(), value domain:mapping {
                          }, raw bools:false, Unit:(), Unit:()]
 Difference: [readwrite * write:({}, All mutexes), Apron:top (env: [||]),
              Unit:(), Unit:(), Unit:(), value domain:mapping {
                                                        }, raw bools:false,
              Unit:(), Unit:()] instead of [Apron:bottom (env: [|0> i:int|]),
                                            readwrite * write:({}, All mutexes),
                                            value domain:mapping {
                                                           Global {
                                                             _IO_2_1_stdin_ ->
                                                               mapping {
                                                                 }
                                                             _IO_2_1_stdout_ ->
                                                               mapping {
                                                                 }
                                                             _IO_2_1_stderr_ ->
                                                               mapping {
                                                                 }
                                                             stdin ->
                                                               {NULL, ?}
                                                             stdout ->
                                                               {NULL, ?}
                                                             stderr ->
                                                               {NULL, ?}
                                                             sys_nerr ->
                                                               (Unknown int([-31,31]))
                                                             sys_errlist ->
                                                               (Array: {}, (Unknown int([-63,63])))
                                                             __tzname ->
                                                               (Array: {}, (2))
                                                             __daylight ->
                                                               (Unknown int([-31,31]))
                                                             __timezone ->
                                                               (Unknown int([-63,63]))
                                                             tzname ->
                                                               (Array: {}, (2))
                                                             daylight ->
                                                               (Unknown int([-31,31]))
                                                             timezone ->
                                                               (Unknown int([-63,63]))
                                                             _sys_siglist ->
                                                               (Array: {}, (65))
                                                             sys_siglist ->
                                                               (Array: {}, (65))
                                                             i ->   (0)
                                                           }
                                                         }, Unit:(), Unit:(),
                                            Unit:(), raw bools:false, Unit:(),
                                            Unit:()]
```

With default apron privatization or disabled apron privatization, there are no issues.

Beyond this, once the library analysis of @jerhard is in place, we might have some analysis results for functions that set the type of a mutex, and we should remain sound in such settings.

### PR DESCRIPTION
**Pull request by michael-schwarz**
This fixes the issue that all flavors of mutex-meet privatizations were unsound when using re-entrant locks.

The fix in itself is quite simply: For a mutex that is already held, no `Events.Lock e` is emitted. Thus the privatizations do not unsoundly meet the local value with the value stored at the unknown for a mutex.

This also adds `pthread_mutexattr_settype`  and `pthread_mutexattr_init` to the list of library functions.

Fixes #454

### CODE REVIEW

File: src/domains/events.ml [hunk 1]
```diff
@@ -9,7 +9,7 @@ type t =
   | AssignSpawnedThread of lval * ThreadIdDomain.Thread.t (** Assign spawned thread's ID to lval. *)
 
 let pretty () = function
-  | Lock m -> dprintf "Lock %a" LockDomain.Addr.pretty m
+  | Lock m -> dprintf "Lock %a" LockDomain.Addr.pretty m (* This is only emitted if the mutex was not previously held *)
```
Comment (sim642) [inline src/domains/events.ml:12]: This should be a documentation comment on the constructor in the type definition above, not in the `pretty` implementation.

File: src/analyses/libraryFunctions.ml [hunk 2]
```diff
@@ -193,7 +193,9 @@ let invalidate_actions = ref [
     "_spin_lock_irqsave", readsAll;(*safe*)
     "_spin_unlock_irqrestore", readsAll;(*safe*)
     "pthread_mutex_init", readsAll;(*safe*)
-    "pthread_mutex_destroy", readsAll;(*safe*)
+    "pthread_mutex_init", readsAll;(*safe*)
```
Comment (sim642) [inline src/analyses/libraryFunctions.ml:196]: Now `pthread_mutex_init` is here twice and `pthread_mutex_destroy` isn't at all?

Comment (michael-schwarz) [reply src/analyses/libraryFunctions.ml]: yup, that was a stupid typo

**Review by sim642 — APPROVED** [review]
