### PR TITLE
Make Address Representatives Use Unit-domain for Index-Offsets

### LINKED ISSUE #925: Address set meet unsound for addresses with different int domains active
The meet of the address set is unsound for addresses when different integer domains are active in these addresses. An example is given [here](https://github.com/goblint/analyzer/blob/3dd39e7abbe813ad63fe0137e6a1e17fcaa506c1/tests/regression/29-svcomp/31-dd-address-meet.c).

### PR DESCRIPTION
**Pull request by jerhard**
This PR makes the `NormalLatRepr` use the `Unit`-domain for the index-offset of representatives. This way, the active integer domains do not have an impact on the representative that addresses are grouped with.

Fixes #925. This is the more elegant alternative to #924. I created it separately here because we are already benchmarking #924 and might want to merge #924 first to make it part of the Goblint version submitted to sv-comp.

When we merge #924 first, I will adapt this PR to be able to be merged.

### CODE REVIEW

File: src/cdomains/lval.ml [hunk 1]
```diff
@@ -105,7 +111,7 @@ struct
     | `Index(i,o) -> NoOffset (* array domain can not deal with this -> leads to being handeled as access to unknown part *)
 end
 
-module Offset (Idx: IntDomain.Z) =
+module Offset (Idx: IdxDomain) =
```
Comment (sim642) [inline src/cdomains/lval.ml:114]: It's nice that this can be weakened from `IntDomain.Z`. I was afraid we might need a full `IntDomain.Z` implementation for unit.

File: src/cdomains/lval.ml [hunk 2]
```diff
@@ -382,25 +388,38 @@ struct
...
-    include Normal (Idx)
     type elt = t
 
-    let rec of_elt_offset: Offs.t -> Offs.t =
+    (* Offset module for representative without abstract values for index offsets, i.e. with unit index offsets.
+       Reason: The offset in the representative (used for buckets) should not depend on the integer domains,
+       since different integer domains may be active at different program points. *)
+    include Normal (UnitIdxDomain)
+
+    let rec of_elt_offset (*: (fieldinfo, Idx.t) offs -> (fieldinfo, UnitIdxDomain.t) offs *) =
```
Comment (sim642) [inline src/cdomains/lval.ml:411]: Does this type signature not work anymore or?

File: src/cdomains/lval.ml [hunk 3]
```diff
@@ -382,25 +388,38 @@ struct
...
       | `NoOffset -> `NoOffset
       | `Field (f,o) -> `Field (f, of_elt_offset o)
-      | `Index (_,o) -> `Index (Idx.top (), of_elt_offset o) (* all indices to same bucket *)
-    let of_elt = function
+      | `Index (_,o) -> `Index (UnitIdxDomain.top (), of_elt_offset o) (* all indices to same bucket *)
+
+    let of_elt (x: elt): t = match x with
       | Addr (v, o) -> Addr (v, of_elt_offset o) (* addrs grouped by var and part of offset *)
       | StrPtr _ when GobConfig.get_bool "ana.base.limit-string-addresses" -> StrPtr None (* all strings together if limited *)
-      | a -> a (* everything else is kept separate, including strings if not limited *)
```
Comment (sim642) [inline src/cdomains/lval.ml:403]: We should keep this comment about the now-three remaining cases.

**Review by sim642 — COMMENTED** [review]
Since #924 was merged for SV-COMP, this now has merge conflicts.

File: src/cdomains/lval.ml (hunk 2 above)
Comment (jerhard) [reply src/cdomains/lval.ml]: It actually works, so I re-added it.

File: src/cdomains/lval.ml (hunk 3 above)
Comment (jerhard) [reply src/cdomains/lval.ml]: I re-added the comment.

**Review by sim642 — APPROVED** [review]
