### PR TITLE
Invalidate variables that are assigned return values of `pthread_create(...)` and `pthread_join(...)`

### LINKED ISSUE #387: Missing invalidate of assigned variable on `pthread_join`
The variable that the return value of a `pthread_join` operation is assigned to needs to be invalidated, as it is assigned either `0` or an error code, depending on whether `pthread_join` succeeded. It currently is not.

Minimal example:
https://github.com/goblint/analyzer/blob/79c30aae5e75c15661f3eac4b4db8db39351b856/tests/regression/01-cpa/54-tid-invalidate.c#L1-L16

### PR DESCRIPTION
**Pull request by michael-schwarz**
Previously the invalidation in these two cases was missing.

For most library functions the invalidation is done by default as `special` falls through to the default case.
https://github.com/goblint/analyzer/blob/2e8aa66c46643d6774f3c60e70f988004aa121a9/src/analyses/base.ml#L2250

For these two, however, the call needs to be made explicit.

Closes #387

### CODE REVIEW

File: src/analyses/base.ml [hunk 1]
```diff
@@ -2170,21 +2175,24 @@ struct
...
+          | `Address ret_a ->
+            begin match eval_rv (Analyses.ask_of_ctx ctx) gs st id with
+              | `Thread a ->
+                let a = List.fold AD.join (AD.bot ()) (List.map (fun x -> AD.from_var (ThreadIdDomain.Thread.to_varinfo x)) (ValueDomain.Threads.elements a)) in
+                (* TODO: is this type right? *)
+                set ~ctx:(Some ctx) (Analyses.ask_of_ctx ctx) gs st ret_a (Cilfacade.typeOf ret_var) (get (Analyses.ask_of_ctx ctx) gs st a None)
+              | _      -> invalidate ~ctx (Analyses.ask_of_ctx ctx) gs st [ret_var]
+            end
+          | _      -> invalidate ~ctx (Analyses.ask_of_ctx ctx) gs st [ret_var]
+        end
```
Comment (sim642) [inline src/analyses/base.ml:2193]: You can get rid of the outer `begin...end` and one level of indentation now because it's inside `let`.

**Review by sim642 — APPROVED** [review]
