### PR TITLE
`UnionDomain.meet`: Throw `Uncomparable` exception for abstract unions with different active fields

### LINKED ISSUE #1105: Use of `UnionDomain.meet` in refinement causes unsoundness and crashes
The refinement that is done when encountering branching uses `UnionDomain.meet`, which currently causes unsound behavior and crashes. 

In the following example, Goblint considers both branches of the `if` to be dead:

https://github.com/goblint/analyzer/blob/b45d527d1e4d6f66fe0e0e035376bfbd8c45d0cc/tests/regression/27-inv_invariants/18-union-float-int.c#L9-L18

The reason is that the meet of a: $(field: x, value: 12)$ and b: $(field: f, value: 129.0)$ yields $(field: \bot, value: \bot)$.

In an example where the union type contains either a `char` or an `int`, Goblint crashes with a `IncompatibleIkind`-exception, because the abstract values with `ikinds`  of `Char` and `Int` are passed to a `meet`.
https://github.com/goblint/analyzer/blob/b45d527d1e4d6f66fe0e0e035376bfbd8c45d0cc/tests/regression/27-inv_invariants/19-union-char-int.c#L3-L18

### PR DESCRIPTION
**Pull request by jerhard**
**Edit:** This PR changes the `meet` of the `UnionDomain` such that it throws a `Uncomparable` exception, as suggested below: https://github.com/goblint/analyzer/pull/1109#discussion_r1260266161. The `BaseInvariant` that uses the `VD.meet` catches the `Uncomparable` exception and does not do a refinement in case it is thrown.

On test case `27/18` both branches of an `if` comparing two unions are no longer considered dead, and test `27/19` does no longer crashes with the `IncompatbileIkindException`. 
   
Fixes #1105.

<details> 
<summary>Previous Approach</summary>

~~This adds a function `ValueDomain.try_meet`, a version of the `meet` that may fail for unions with different active fields and use it in BaseInvariant.  @michael-schwarz and I discussed this today.~~
    
~~The refinement by BaseInvariant to handle branching used VD.meet, which caused issue #1105, due to the behavior of UnionDomain.meet: The meet of unions with different active fields can result in a bottom value.
This led to e.g. spuriously dead code.~~
    
 ~~This adds a function `try_meet` to the `VvalueDomain`, the union domain, and those domains that may contain a union domain element: structs, arrays, blobs. The function `try_meet` in the union domain throws an exception if the fields of the unions for which a meet was tried do not coincide.~~
 </details>

### CODE REVIEW

**Comment by jerhard** [comment]
The exact behavior on `27/19` may be investigated further in the future, as currently, Goblint claims that for the following `if` always evaluates to `true`:

https://github.com/goblint/analyzer/blob/14929ca3bf9219edd9c19d15a29bf0448784b211/tests/regression/27-inv_invariants/19-union-char-int.c#L3-L18

Whether this actually holds may e.g. depend on the endianness of the machine. But this is a separate issue.

File: src/analyses/baseInvariant.ml [hunk 1]
```diff
@@ -83,7 +83,11 @@ struct
       in
       let state_with_excluded = set a gs st addr t_lval value ~ctx in
       let value =  get a gs state_with_excluded addr None in
-      let new_val = apply_invariant oldval value in
+      let new_val =
+        try
+          apply_invariant oldval value
+        with PreValueDomain.NotMeetable -> oldval
```
Comment (sim642) [inline src/analyses/baseInvariant.ml:89]: Seems to me like `Lattice.Uncomparable` already exists for this precise meaning:
https://github.com/goblint/analyzer/blob/3af00a86da65ab5caac033b0ecff02dc69c3bfbf/src/domains/lattice.ml#L14-L15
Just using that exception would avoid the need for littering interfaces with some special `try_meet` because `meet` is allowed to raise `Uncomparable`.

Then `try_meet` could just be a helper function here which has such fallback. Right now that code is repeated multiple times.

Comment (jerhard) [reply src/analyses/baseInvariant.ml]: Yes, that is much more concise indeed. I adapted the implementation accordingly.

File: src/cdomains/unionDomain.ml [hunk 2]
```diff
@@ -15,16 +15,29 @@ sig
...
 module Simple (Values: Arg) =
 struct
   include Lattice.Prod (Field) (Values)
   type value = Values.t
 
+  let meet (f, x) (g, y) =
+    let field = Field.meet f g in
+    let value = Values.meet x y in
+    (field, value)
+
```
Comment (sim642) [inline src/cdomains/unionDomain.ml:40]: Isn't this the default `Lattice.Prod.meet` anyway?

Comment (jerhard) [reply src/cdomains/unionDomain.ml]: This is right, I removed the explicit definition.

**Review by sim642 — APPROVED** [review]

**Comment by jerhard** [comment]
I had to readd the explicit `meet` on `master` since otherwise it would not be ensured that the `meet` is first performed on the `Field`, leading to `IncompatibleIkind` exceptions, where `Lattice.Uncomparable` exceptions should be thrown.
