### PR TITLE
Fix int domain test failures

### LINKED ISSUE #575: Int domain failures with many ikinds
- [x] Interval `rem` fails with `long` and `long long`:
   ```
   test `integerset -> intervals (long): valid rem` failed on ≥ 1 cases:
   ([-1L], [-1L]) (after 124 shrink steps)
   
   test `integerset -> intervals (long long): valid rem` failed on ≥ 1 cases:
   ([-1L], [-1L]) (after 124 shrink steps)
   ```
   This is due to some precision improvement to it: https://github.com/goblint/analyzer/pull/568#issuecomment-1021448988.

- [x] Def_exc `bitnot` fails with `unsigned int`:
   ```
   test `integerset -> def_exc (unsigned int): valid bitnot`
   failed on ≥ 1 cases: [0L] (after 63 shrink steps)
   ```

- [x] Congruence fails arithmetic with `unsigned int`:
    ```
    test `integerset -> congruences (unsigned int): valid bitnot`
    failed on ≥ 1 cases: [0L] (after 64 shrink steps)

    test `integerset -> congruences (unsigned int): valid sub`
    failed on ≥ 1 cases: ([0L], [7795773234L]) (after 92 shrink steps)

    test `integerset -> congruences (unsigned int): valid mul`
    failed on ≥ 1 cases: ([-1L], [7795773234L]) (after 91 shrink steps)

    test `integerset -> congruences (unsigned int): valid add`
    failed on ≥ 1 cases: ([0L], [7795773234L]) (after 92 shrink steps)

    test `integerset -> congruences (unsigned int): valid neg`
    failed on ≥ 1 cases: [-7458869127L] (after 30 shrink steps)
    ```

- [x] Enums fails comparisons with `unsigned int`:
    ```
    test `integerset -> enums (unsigned int): valid ge` failed on ≥ 1 cases:
    ([0L], [-1L]) (after 72 shrink steps)

    test `integerset -> enums (unsigned int): valid le` failed on ≥ 1 cases:
    ([0L], [-1L]) (after 72 shrink steps)

    test `integerset -> enums (unsigned int): valid gt` failed on ≥ 1 cases:
    ([0L], [-1L]) (after 72 shrink steps)

    test `integerset -> enums (unsigned int): valid lt` failed on ≥ 1 cases:
    ([0L], [-1L]) (after 72 shrink steps)
    ```

- [x] Interval fails comparisons and `div`/`rem` with `unsigned int`:
    ```
    test `integerset -> intervals (unsigned int): valid ge`
    failed on ≥ 1 cases: ([0L], [-1L]) (after 72 shrink steps)

    test `integerset -> intervals (unsigned int): valid le`
    failed on ≥ 1 cases: ([0L], [-1L]) (after 72 shrink steps)

    test `integerset -> intervals (unsigned int): valid gt`
    failed on ≥ 1 cases: ([0L], [-1L]) (after 72 shrink steps)

    test `integerset -> intervals (unsigned int): valid lt`
    failed on ≥ 1 cases: ([0L], [-1L]) (after 72 shrink steps)

    test `integerset -> intervals (unsigned int): valid rem`
    failed on ≥ 1 cases:
    ([72766417L], [589514379985750L]) (after 25 shrink steps)

    test `integerset -> intervals (unsigned int): valid div`
    failed on ≥ 1 cases:
    ([72766417L], [589514379985750L]) (after 25 shrink steps)
    ```

- [x] Similar failures for other unsigned types.
- [x] 46 failures for `IBool`.
---

Ideally all of this could be enabled and should succeed the domain tests:
https://github.com/goblint/analyzer/blob/3605784730fbebbf918d20964ad30928278ae049/unittest/maindomaintest.ml#L84-L98

### PR DESCRIPTION
**Pull request by sim642**
Closes #575.

### CODE REVIEW

File: src/cdomains/intDomain.ml [hunk 1]
```diff
@@ -552,7 +552,7 @@ struct
               top_of ik
         else if not cast && should_ignore_overflow ik then
           let tl, tu = BatOption.get @@ top_of ik in
-          Some (max tl x, min tu y)
+          Some (Ints_t.max tl x, Ints_t.min tu y)
```
Comment (michael-schwarz) [inline src/cdomains/intDomain.ml:555]: Are all these insertions fo `Ints_t` simply to clarify what is going on, or where they related to a bug?

File: src/cdomains/intDomain.ml [hunk 2]
```diff
@@ -1317,7 +1317,16 @@ struct
...
           (* Perform a wrap-around for unsigned values and for signed values (if configured). *)
           let mapped_excl = S.map (fun excl -> BigInt.cast_to ik excl) s in
-          `Excluded (mapped_excl, r)
+          match ik with
+          | IBool ->
+            begin match S.mem BigInt.zero mapped_excl, S.mem BigInt.one mapped_excl with
+              | false, false -> `Excluded (mapped_excl, r) (* Not {} -> Not {} *)
+              | true, false -> `Definite BigInt.one (* Not {0} -> 1 *)
+              | false, true -> `Definite BigInt.zero (* Not {1} -> 0 *)
+              | true, true -> `Bot (* Not {0, 1} -> bot *)
```
Comment (michael-schwarz) [inline src/cdomains/intDomain.ml:1326]: Are we sure this is only ever called with a value that is normalized before, and not some normal integer that was computed somewhere else where `Not {0,1}` would be truthy?

File: src/cdomains/intDomain.ml [hunk 3]
```diff
@@ -1734,13 +1743,25 @@ module Enums : S with type int_t = BigInt.t = struct
...
+         in
+         let r_min, r_max = min_of_range r, max_of_range r in
+         assert (range_in_ikind r && BISet.for_all (value_in_range (r_min, r_max)) xs); *)
+      begin match ikind with
+        | IBool ->
+          begin match BISet.mem BigInt.zero xs, BISet.mem BigInt.one xs with
+            | false, false -> top_bool  (* Not {} -> {0, 1} *)
+            | true, false -> Inc (BISet.singleton BigInt.one) (* Not {0} -> {1} *)
+            | false, true -> Inc (BISet.singleton BigInt.zero) (* Not {1} -> {0} *)
+            | true, true -> bot_of ikind (* Not {0, 1} -> bot *)
```
Comment (michael-schwarz) [inline src/cdomains/intDomain.ml:1759]: Same as for `DefExc` above

File: src/cdomains/intDomain.ml [hunk 4]
```diff
@@ -2236,27 +2257,28 @@ struct
...
         let x = (Ints_t.bitand (max_int ik) (Ints_t.shift_left Ints_t.one (Ints_t.to_int c'))) in   (* 2^c' *)
-        if is_prime (m' +: Ints_t.one) then
-          Some (x *: c, Ints_t.gcd (x *: m) ((c *: x) *: (m' +: Ints_t.one)))
-        else
-          Some (x *: c, Ints_t.gcd (x *: m) (c *: x))
+        (* TODO: commented out because fails test with _Bool *)
+        (* if is_prime (m' +: Ints_t.one) then
+          normalize ik @@ Some (x *: c, Ints_t.gcd (x *: m) ((c *: x) *: (m' +: Ints_t.one)))
+        else *)
+          normalize ik @@ Some (x *: c, Ints_t.gcd (x *: m) (c *: x))
```
Comment (michael-schwarz) [inline src/cdomains/intDomain.ml:2281]: Why not just have a special case for bool here? Shifting a bool should not change its value (at least it doesn't on GCC).

File: src/cdomains/intDomain.ml (hunk 1 above)
Comment (sim642) [reply src/cdomains/intDomain.ml:555]: I didn't observe a bug, but just noticed that the previous ones were calling the polymorphic `Stdlib.max`, which internally uses polymorphic comparison instead of `Ints_t.compare`. Better safe than sorry with these on bigints.

File: src/cdomains/intDomain.ml (hunk 4 above)
Comment (sim642) [reply src/cdomains/intDomain.ml:2281]: Because I'm not sure if the first case is right in general. Left shifting `1` (`1+0Z`) by `Z` (`0+1Z`) gives `1+2Z` according to it, but it's clearly wrong: any non-zero left shift would make it even. The same could happen with larger types as well, but their generators probably just don't happen to generate such arguments.

File: src/cdomains/intDomain.ml (hunk 2 above)
Comment (sim642) [reply src/cdomains/intDomain.ml:1326]: Not sure what you mean. The `mapped_excl` above normalizes the values to the ikind and this is only done for `IBool`, which only has the values 0 and 1 after normalizing.

**Comment by michael-schwarz** [comment]
Related: #99

**Comment by sim642** [comment]
Ugh, ok. That's what we get for disabling the complete unlocked workflor for PRs. I'll fix it on master.
